/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.work;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author hernan
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Menu");
        setSize(500, 350);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel();
        add(panel);

        JButton openJavaViewButton = new JButton("Open JavaView");
        panel.add(openJavaViewButton);

        openJavaViewButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JavaView hola = new JavaView();
                hola.setVisible(true);
            }
        });
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            Menu menu = new Menu();
            menu.setVisible(true);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cordinador = new javax.swing.JButton();
        Trainer = new javax.swing.JButton();
        Camper = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Hiragino Sans", 2, 18)); // NOI18N
        jLabel7.setText("Identificacion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        jLabel1.setFont(new java.awt.Font("Kannada Sangam MN", 2, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        jLabel8.setFont(new java.awt.Font("Hiragino Sans", 2, 18)); // NOI18N
        jLabel8.setText("Ingrese a que perfil desea ingresar");

        Cordinador.setFont(new java.awt.Font("Kannada Sangam MN", 2, 18)); // NOI18N
        Cordinador.setText("Cordinador");
        Cordinador.setActionCommand("loadData");
        Cordinador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CordinadorMouseClicked(evt);
            }
        });
        Cordinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CordinadorActionPerformed(evt);
            }
        });

        Trainer.setFont(new java.awt.Font("Kannada Sangam MN", 2, 18)); // NOI18N
        Trainer.setText("Trainer");
        Trainer.setActionCommand("loadData");
        Trainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrainerMouseClicked(evt);
            }
        });
        Trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerActionPerformed(evt);
            }
        });

        Camper.setFont(new java.awt.Font("Kannada Sangam MN", 2, 18)); // NOI18N
        Camper.setText("Camper");
        Camper.setActionCommand("loadData");
        Camper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CamperMouseClicked(evt);
            }
        });
        Camper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(89, 89, 89))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Camper, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trainer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cordinador, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Cordinador, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Trainer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Camper, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CordinadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CordinadorMouseClicked

    }//GEN-LAST:event_CordinadorMouseClicked

    private void CordinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CordinadorActionPerformed
        JavaView menu = new JavaView();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CordinadorActionPerformed

    private void TrainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrainerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainerMouseClicked

    private void TrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainerActionPerformed

    private void CamperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CamperMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CamperMouseClicked

    private void CamperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamperActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Camper;
    public javax.swing.JButton Cordinador;
    public javax.swing.JButton Trainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
